import React, {useMemo} from 'react';
import { View, Pressable, StyleSheet, Switch } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen, Txt, GlassCard, Pill, Button, SectionTitle } from '../components/UI';
import { COLORS } from '../theme';
import { ARTISTS, MAP_SPOTS, MERCH, REWARDS, ANNOUNCEMENTS } from '../data';

export default function DetailScreen({route,state,actions,goBack}){
 if(route.name==='artist')return <Artist route={route} state={state} actions={actions} goBack={goBack}/>;
 if(route.name==='map')return <Map goBack={goBack}/>;
 if(route.name==='merch')return <Merch state={state} actions={actions} goBack={goBack}/>;
 if(route.name==='rewards')return <Rewards state={state} actions={actions} goBack={goBack}/>;
 if(route.name==='crew')return <Crew state={state} actions={actions} goBack={goBack}/>;
 if(route.name==='notifications')return <Notifications goBack={goBack}/>;
 if(route.name==='memories')return <Memories goBack={goBack}/>;
 return <Profile state={state} actions={actions} goBack={goBack}/>;
}

function Header({title,sub,goBack,right}){return <View style={styles.header}><Pressable onPress={goBack} style={styles.back}><Ionicons name="chevron-back" size={20} color="#fff"/></Pressable><View style={{flex:1}}><Txt faint style={styles.headSub}>{sub}</Txt><Txt style={styles.headTitle}>{title}</Txt></View>{right||<View style={{width:42}}/>}</View>}

function Artist({route,state,actions,goBack}){const a=ARTISTS.find(x=>x.id===route.params?.artistId)||ARTISTS[0];const fav=state.favourites.includes(a.id);return <Screen><Header title={a.name} sub={a.tag} goBack={goBack}/><GlassCard style={{minHeight:360,justifyContent:'flex-end',overflow:'hidden'}}><View style={[styles.bigGlow,{backgroundColor:a.accent}]}/><Txt faint style={{fontSize:10,fontWeight:'900',letterSpacing:1.4}}>{a.meta}</Txt><Txt style={{fontSize:38,fontWeight:'1000',letterSpacing:-2,marginTop:8}}>{a.name}</Txt><Txt muted style={{fontSize:13,lineHeight:20,marginTop:12,maxWidth:330}}>{a.bio}</Txt></GlassCard><Button title={fav?'REMOVE FROM MY XXL':'ADD TO MY XXL'} icon={fav?'heart':'heart-outline'} onPress={()=>actions.toggleFavourite(a.id)} style={{marginTop:12}}/><Button title="REMIND ME 15 MIN BEFORE" secondary icon="notifications-outline" onPress={()=>actions.toggleReminder('artist:'+a.id)} style={{marginTop:9}}/></Screen>}

function Map({goBack}){const [selected,setSelected]=React.useState(MAP_SPOTS[1]);return <Screen><Header title="VENUE MAP" sub="ARENA TAKEDOWN" goBack={goBack}/><GlassCard style={styles.map}><View style={styles.arena}><Txt faint style={{fontSize:9,fontWeight:'900',letterSpacing:2}}>OSTRAVAR ARÉNA · CONCEPT MAP</Txt>{MAP_SPOTS.map(p=><Pressable key={p.id} onPress={()=>setSelected(p)} style={[styles.pin,{left:`${p.x}%`,top:`${p.y}%`},selected.id===p.id&&styles.pinActive]}><Txt style={[styles.pinText,selected.id===p.id&&{color:'#050505'}]}>{p.zone}</Txt></Pressable>)}<View style={styles.stage}><Txt style={{fontSize:10,fontWeight:'1000'}}>MAIN STAGE</Txt></View></View></GlassCard><GlassCard style={{marginTop:12}}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><View style={styles.detailIcon}><Ionicons name={selected.icon} size={20} color="#fff"/></View><View style={{flex:1}}><Txt style={{fontWeight:'900',fontSize:16}}>{selected.name}</Txt><Txt muted style={{fontSize:11,marginTop:4}}>{selected.sub}</Txt></View><Pill>ZONE {selected.zone}</Pill></View></GlassCard><SectionTitle eyebrow="LOCATIONS" title="All venue points"/>{MAP_SPOTS.map(p=><Pressable key={p.id} onPress={()=>setSelected(p)} style={styles.location}><Ionicons name={p.icon} size={18} color="#fff"/><View style={{flex:1}}><Txt style={{fontWeight:'800'}}>{p.name}</Txt><Txt muted style={{fontSize:10,marginTop:2}}>{p.sub}</Txt></View><Txt faint style={{fontWeight:'900'}}>{p.zone}</Txt></Pressable>)}</Screen>}

function Merch({state,actions,goBack}){return <Screen><Header title="XXL MERCH" sub="ARENA TAKEDOWN CAPSULE" goBack={goBack}/><Txt muted style={{fontSize:12,lineHeight:19}}>Reserve event-exclusive pieces now and pick them up inside the venue. Prototype reservations are saved locally.</Txt><SectionTitle eyebrow="DROP 01" title="Limited capsule"/>{MERCH.map((m,i)=>{const reserved=state.reservedMerch.includes(m.id);return <GlassCard key={m.id} style={{marginBottom:11,padding:0,overflow:'hidden'}}><View style={styles.merchArt}><Txt style={{fontSize:48,fontWeight:'1000',letterSpacing:-3}}>XXL</Txt><Txt faint style={{fontSize:9,fontWeight:'900',letterSpacing:2}}>{m.tag}</Txt></View><View style={{padding:17}}><Txt faint style={{fontSize:9,fontWeight:'900'}}>{m.size}</Txt><Txt style={{fontSize:18,fontWeight:'900',marginTop:5}}>{m.name}</Txt><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:14}}><Txt style={{fontSize:16,fontWeight:'1000'}}>{m.price.toLocaleString('cs-CZ')} Kč</Txt><Pressable onPress={()=>actions.toggleMerch(m.id)} style={[styles.reserve,reserved&&styles.reserveActive]}><Txt style={{fontSize:9,fontWeight:'900',color:reserved?'#050505':'#fff'}}>{reserved?'RESERVED':'RESERVE'}</Txt></Pressable></View></View></GlassCard>})}</Screen>}

function Rewards({state,actions,goBack}){return <Screen><Header title="XXL REWARDS" sub="MEMBER LEVEL" goBack={goBack} right={<Pill>{state.points} XP</Pill>}/><GlassCard style={styles.levelCard}><View style={styles.levelRing}><Txt style={{fontSize:25,fontWeight:'1000'}}>{state.level}</Txt></View><View style={{flex:1}}><Txt faint style={{fontSize:9,fontWeight:'900',letterSpacing:1.2}}>CURRENT LEVEL</Txt><Txt style={{fontSize:24,fontWeight:'1000',marginTop:4}}>XXL INSIDER</Txt><Txt muted style={{fontSize:11,lineHeight:17,marginTop:6}}>Earn XP from events, merch and drops. Level {state.level+1} unlocks at {(state.level+1)*1000} XP.</Txt></View></GlassCard><SectionTitle eyebrow="REDEEM" title="Member rewards"/>{REWARDS.map(r=><GlassCard key={r.id} style={{marginBottom:10}}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><View style={styles.detailIcon}><Ionicons name={r.icon} size={20} color="#fff"/></View><View style={{flex:1}}><Txt style={{fontWeight:'900'}}>{r.name}</Txt><Txt muted style={{fontSize:11,marginTop:3}}>{r.points} XP</Txt></View><Pill active={state.points>=r.points}>{state.points>=r.points?'UNLOCKED':'LOCKED'}</Pill></View></GlassCard>)}</Screen>}

function Crew({state,actions,goBack}){const crew=[['Šimi','YOU','Entrance'],['Alex','ONLINE','Main Stage'],['Tom','ONLINE','Merch'],['Isa','OFFLINE','—']];return <Screen><Header title="MY CREW" sub="XXL TOGETHER" goBack={goBack}/><GlassCard><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><View style={{flex:1}}><Txt style={{fontWeight:'900',fontSize:16}}>Share my festival zone</Txt><Txt muted style={{fontSize:11,lineHeight:17,marginTop:4}}>Share only your selected venue zone with your crew.</Txt></View><Switch value={state.crewShare} onValueChange={actions.setCrewShare} trackColor={{false:'#2A2A30',true:'#F23A4B'}} thumbColor="#fff"/></View></GlassCard><SectionTitle eyebrow="4 MEMBERS" title="Crew status"/>{crew.map((c,i)=><View key={c[0]} style={styles.crewRow}><View style={styles.crewAvatar}><Txt style={{fontWeight:'1000'}}>{c[0][0]}</Txt></View><View style={{flex:1}}><Txt style={{fontWeight:'900'}}>{c[0]}</Txt><Txt faint style={{fontSize:9,marginTop:3}}>{c[1]}</Txt></View><View style={{alignItems:'flex-end'}}><Txt style={{fontWeight:'800',fontSize:11}}>{i===0?(state.crewShare?'Entrance':'Hidden'):c[2]}</Txt><Txt faint style={{fontSize:9,marginTop:3}}>ZONE</Txt></View></View>)}</Screen>}

function Notifications({goBack}){return <Screen><Header title="NOTIFICATIONS" sub="XXL NOW" goBack={goBack}/>{ANNOUNCEMENTS.map((a,i)=><GlassCard key={a.id} style={{marginBottom:10}}><View style={{flexDirection:'row',gap:12}}><View style={styles.detailIcon}><Ionicons name={a.type==='MERCH'?'shirt-outline':a.type==='DROP'?'sparkles-outline':'megaphone-outline'} size={19} color="#fff"/></View><View style={{flex:1}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Txt style={{fontWeight:'900',fontSize:15}}>{a.title}</Txt>{i<2&&<View style={styles.unread}/>}</View><Txt muted style={{fontSize:11,lineHeight:17,marginTop:5}}>{a.body}</Txt></View></View></GlassCard>)}</Screen>}

function Memories({goBack}){return <Screen><Header title="MEMORIES" sub="YOUR XXL RECAP" goBack={goBack}/><GlassCard style={styles.memoryHero}><Txt faint style={{fontSize:9,fontWeight:'900',letterSpacing:1.5}}>POST-EVENT PREVIEW</Txt><Txt style={{fontSize:38,fontWeight:'1000',letterSpacing:-2,marginTop:14}}>YOU WERE{`\n`}THERE.</Txt><Txt muted style={{lineHeight:20,marginTop:12}}>After Arena Takedown, this space becomes your personal recap with official media and event stats.</Txt></GlassCard><SectionTitle eyebrow="YOUR XXL 2027" title="Recap preview"/><View style={styles.statGrid}><MemoryStat n="7" t="ARTISTS"/><MemoryStat n="8H" t="IN ARENA"/><MemoryStat n="3" t="DROPS"/><MemoryStat n="2.4K" t="XP"/></View></Screen>}

function Profile({state,actions,goBack}){return <Screen><Header title="PROFILE" sub="XXL MEMBER" goBack={goBack}/><GlassCard><View style={{flexDirection:'row',alignItems:'center',gap:14}}><View style={styles.profileAvatar}><Txt style={{color:'#050505',fontWeight:'1000',fontSize:19}}>ŠS</Txt></View><View style={{flex:1}}><Txt style={{fontSize:18,fontWeight:'1000'}}>Šimon Szábo</Txt><Txt muted style={{fontSize:11,marginTop:3}}>XXL Insider · Pass XXL-001</Txt></View><Pill active>ACTIVE</Pill></View></GlassCard><SectionTitle eyebrow="PREFERENCES" title="Festival settings"/><GlassCard><Setting title="Preview LIVE mode" sub="Transform Home into the live festival view." value={state.livePreview} onValue={actions.setLive}/><Setting title="Share crew zone" sub="Show only your selected venue zone." value={state.crewShare} onValue={actions.setCrewShare} last/></GlassCard><Button title="RESET LOCAL DEMO DATA" secondary onPress={actions.reset} style={{marginTop:12}}/></Screen>}
function Setting({title,sub,value,onValue,last}){return <View style={[styles.setting,!last&&styles.settingBorder]}><View style={{flex:1}}><Txt style={{fontWeight:'900'}}>{title}</Txt><Txt muted style={{fontSize:11,lineHeight:17,marginTop:3}}>{sub}</Txt></View><Switch value={value} onValueChange={onValue} trackColor={{false:'#2A2A30',true:'#F23A4B'}} thumbColor="#fff"/></View>}
function MemoryStat({n,t}){return <GlassCard style={{width:'48%',alignItems:'center'}}><Txt style={{fontSize:26,fontWeight:'1000'}}>{n}</Txt><Txt faint style={{fontSize:8,fontWeight:'900',letterSpacing:1.2,marginTop:5}}>{t}</Txt></GlassCard>}

const styles=StyleSheet.create({header:{height:92,flexDirection:'row',alignItems:'center',gap:12},back:{height:42,width:42,borderRadius:21,backgroundColor:COLORS.panel2,borderWidth:1,borderColor:COLORS.border,alignItems:'center',justifyContent:'center'},headSub:{fontSize:8,fontWeight:'900',letterSpacing:1.5},headTitle:{fontSize:25,fontWeight:'1000',letterSpacing:-1,marginTop:2},bigGlow:{position:'absolute',width:250,height:250,borderRadius:160,opacity:.12,right:-70,top:-70},map:{padding:10},arena:{height:430,borderRadius:24,backgroundColor:'#0B0B0E',borderWidth:1,borderColor:COLORS.border,alignItems:'center',paddingTop:20,overflow:'hidden'},stage:{position:'absolute',top:65,left:'25%',right:'25%',height:42,borderRadius:12,backgroundColor:'#F23A4B',alignItems:'center',justifyContent:'center'},pin:{position:'absolute',marginLeft:-18,marginTop:-18,width:36,height:36,borderRadius:18,backgroundColor:'#19191F',borderWidth:1,borderColor:COLORS.borderStrong,alignItems:'center',justifyContent:'center'},pinActive:{backgroundColor:'#FFFFFF'},pinText:{fontSize:10,fontWeight:'1000'},detailIcon:{width:40,height:40,borderRadius:14,backgroundColor:'rgba(255,255,255,.07)',alignItems:'center',justifyContent:'center'},location:{minHeight:60,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderColor:COLORS.border},merchArt:{height:190,alignItems:'center',justifyContent:'center',backgroundColor:'#09090C',borderBottomWidth:1,borderColor:COLORS.border},reserve:{borderRadius:999,borderWidth:1,borderColor:COLORS.borderStrong,paddingHorizontal:14,paddingVertical:10},reserveActive:{backgroundColor:'#fff'},levelCard:{flexDirection:'row',gap:16,alignItems:'center'},levelRing:{height:86,width:86,borderRadius:43,borderWidth:8,borderColor:'#fff',alignItems:'center',justifyContent:'center'},crewRow:{minHeight:74,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderColor:COLORS.border},crewAvatar:{height:42,width:42,borderRadius:21,backgroundColor:COLORS.panel2,borderWidth:1,borderColor:COLORS.borderStrong,alignItems:'center',justifyContent:'center'},unread:{width:8,height:8,borderRadius:4,backgroundColor:COLORS.red},memoryHero:{minHeight:330,justifyContent:'flex-end'},statGrid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:10},profileAvatar:{height:56,width:56,borderRadius:28,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},setting:{minHeight:76,flexDirection:'row',alignItems:'center',gap:12},settingBorder:{borderBottomWidth:1,borderColor:COLORS.border}});
