import React from 'react';
import {View,Pressable,StyleSheet,Switch} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {Screen,Txt,GlassCard,Pill,Button,SectionTitle,O2ArenaLogo} from '../components/UI';
import {COLORS} from '../theme';
import {MISSIONS,REWARDS,O2_INFO,EVENT} from '../data';
import {t} from '../i18n';

export default function DetailScreen({route,state,actions,navigate,goBack}){
 if(route.name==='profile')return <Profile state={state} actions={actions} navigate={navigate} goBack={goBack}/>;
 if(route.name==='notifications')return <Notifications state={state} actions={actions} goBack={goBack}/>;
 if(route.name==='venue')return <Venue state={state} actions={actions} goBack={goBack}/>;
 if(route.name==='emergency')return <Emergency state={state} goBack={goBack}/>;
 if(route.name==='wallet')return <Wallet state={state} goBack={goBack}/>;
 if(route.name==='rewards')return <Rewards state={state} goBack={goBack}/>;
 if(route.name==='missions')return <Missions state={state} goBack={goBack}/>;
 if(route.name==='crew')return <Crew state={state} actions={actions} goBack={goBack}/>;
 if(route.name==='merch')return <LockedFeature title={t(state.language,'merch')} state={state} navigate={navigate} goBack={goBack}/>;
 if(route.name==='memories')return <LockedFeature title={t(state.language,'memories')} state={state} navigate={navigate} goBack={goBack}/>;
 return <LockedFeature title="XXL CZECHIA" state={state} navigate={navigate} goBack={goBack}/>;
}
function Header({title,sub,goBack,right}){return <View style={styles.header}><Pressable onPress={goBack} style={styles.back}><Ionicons name="chevron-back" size={20} color="#fff"/></Pressable><View style={{flex:1}}><Txt faint style={styles.sub}>{sub}</Txt><Txt style={styles.title}>{title}</Txt></View>{right||<View style={{width:42}}/>}</View>}
function Profile({state,actions,navigate,goBack}){
 const lang=state.language,guest=!state.session;
 return <Screen><Header title={t(lang,'profile')} sub={guest?t(lang,'guest'):'MY XXL'} goBack={goBack}/>
  {guest?<GlassCard style={styles.center}><View style={styles.bigAvatar}><Ionicons name="person-outline" size={27} color="#fff"/></View><Txt style={styles.profileName}>{t(lang,'guest')}</Txt><Txt muted style={styles.centerCopy}>{t(lang,'guestCopy')}</Txt><Button green title={t(lang,'login')} onPress={()=>navigate('auth',{mode:'login'})} style={{marginTop:18,width:'100%'}}/><Button secondary title={t(lang,'register')} onPress={()=>navigate('auth',{mode:'register'})} style={{marginTop:8,width:'100%'}}/></GlassCard>
  :<><GlassCard><View style={styles.profileRow}><View style={styles.userAvatar}><Txt style={{color:'#050506',fontSize:19,fontWeight:'900'}}>{state.session.name[0]}</Txt></View><View style={{flex:1}}><Txt style={{fontSize:20,fontWeight:'900'}}>{state.session.name}</Txt><Txt muted style={{fontSize:10,marginTop:4}}>@{state.session.username} · {state.session.role.toUpperCase()}</Txt></View><Pill active>{state.passTier}</Pill></View></GlassCard><SectionTitle eyebrow="MY XXL" title={`${state.points} XP`}/><View style={styles.stats}><Stat n={state.favourites.length} t="ARTISTS"/><Stat n={state.completedMissions.length} t="MISSIONS"/><Stat n={state.walletBalance} t="CZK"/><Stat n={state.level} t="LEVEL"/></View><Button secondary title={t(lang,'logout')} onPress={actions.logout} style={{marginTop:12}}/></>}
  <SectionTitle eyebrow={t(lang,'settings').toUpperCase()} title={t(lang,'language')}/>
  <GlassCard><LangRow title="Čeština" active={lang==='cs'} onPress={()=>actions.setLanguage('cs')}/><LangRow title="English" active={lang==='en'} onPress={()=>actions.setLanguage('en')} last/></GlassCard>
  {state.session?.role==='admin'&&<><SectionTitle eyebrow={t(lang,'role').toUpperCase()} title={state.appMode==='admin'?t(lang,'adminMode'):t(lang,'userMode')}/><Button title={state.appMode==='admin'?'SWITCH TO USER MODE':'SWITCH TO ADMIN MODE'} onPress={()=>actions.setAppMode(state.appMode==='admin'?'user':'admin')}/>{state.appMode==='admin'&&<Button secondary title={t(lang,'adminPanel')} onPress={()=>navigate('admin')} style={{marginTop:8}}/>}</>}
 </Screen>
}
function Notifications({state,actions,goBack}){const lang=state.language;return <Screen><Header title={t(lang,'notifications')} sub="XXL NOW" goBack={goBack}/>{state.notifications.map((n,i)=><GlassCard key={n.id} style={{marginBottom:9}}><View style={styles.noteRow}><View style={styles.noteIcon}><Ionicons name={n.type==='LINEUP'?'flash-outline':n.type==='ADMIN'?'megaphone-outline':'calendar-outline'} size={19} color="#fff"/></View><View style={{flex:1}}><Txt style={{fontWeight:'900',fontSize:15}}>{lang==='cs'?n.titleCs:n.titleEn}</Txt><Txt muted style={{fontSize:10,lineHeight:16,marginTop:5}}>{lang==='cs'?n.bodyCs:n.bodyEn}</Txt></View>{!n.read&&<View style={styles.unread}/>}</View></GlassCard>)}<Button secondary title="MARK ALL READ" onPress={actions.markNotificationsRead}/></Screen>}
function Venue({state,actions,goBack}){const lang=state.language;return <Screen><Header title={t(lang,'o2Arena')} sub={t(lang,'officialVenue')} goBack={goBack}/><GlassCard><O2ArenaLogo/><Txt style={{fontSize:16,fontWeight:'900',marginTop:15}}>{EVENT.address}</Txt></GlassCard><SectionTitle eyebrow={t(lang,'transport').toUpperCase()} title={lang==='cs'?'Praktické informace':'Visitor information'}/><GlassCard><Info icon="train-outline" t={O2_INFO.metro}/><Info icon="navigate-outline" t={O2_INFO.tram}/><Info icon="train-outline" t={O2_INFO.train}/><Info icon="enter-outline" t={O2_INFO.entrance}/><Info icon="car-outline" t={O2_INFO.parking} last/></GlassCard><GlassCard style={{marginTop:10,flexDirection:'row',gap:10}}><Ionicons name="information-circle-outline" size={20} color={COLORS.green2}/><Txt muted style={{flex:1,fontSize:10,lineHeight:16}}>{O2_INFO.entry}</Txt></GlassCard>{state.session&&<Button secondary title="MY XXL · VENUE CHECK" onPress={()=>actions.completeMission('m4')} style={{marginTop:10}}/>}</Screen>}
function Emergency({state,goBack}){const lang=state.language;return <Screen><Header title={t(lang,'help')} sub="SAFETY" goBack={goBack}/><GlassCard style={styles.emergency}><Ionicons name="medkit-outline" size={30} color="#fff"/><Txt style={{fontSize:27,fontWeight:'900',marginTop:18}}>{lang==='cs'?'POMOC JE BLÍZKO.':'HELP IS CLOSE.'}</Txt><Txt muted style={{fontSize:11,lineHeight:18,marginTop:7}}>{lang==='cs'?'V případě bezprostředního nebezpečí kontaktujte tísňovou linku. V areně vyhledejte security nebo first aid.':'In immediate danger contact emergency services. Inside the arena, find security or first aid.'}</Txt></GlassCard><SectionTitle eyebrow="O2 ARENA" title={lang==='cs'?'Na místě':'On site'}/><GlassCard><Info icon="medkit-outline" t="First Aid"/><Info icon="shield-outline" t="Security"/><Info icon="search-outline" t="Lost & Found"/><Info icon="exit-outline" t="Emergency exits" last/></GlassCard></Screen>}
function Wallet({state,goBack}){return <Screen><Header title="XXL WALLET" sub="MY XXL" goBack={goBack}/><GlassCard style={styles.center}><Ionicons name="wallet-outline" size={31} color="#fff"/><Txt style={{fontSize:42,fontWeight:'900',letterSpacing:-2,marginTop:18}}>{state.walletBalance} Kč</Txt><Txt muted style={{fontSize:10,marginTop:5}}>Cashless prototype · Admin controls balance</Txt></GlassCard></Screen>}
function Rewards({state,goBack}){const lang=state.language;return <Screen><Header title={t(lang,'rewards')} sub={`${state.points} XP`} goBack={goBack}/>{REWARDS.map(r=><GlassCard key={r.id} style={{marginBottom:9}}><Txt style={{fontSize:16,fontWeight:'900'}}>{lang==='cs'?r.nameCs:r.nameEn}</Txt><Txt muted style={{fontSize:10,marginTop:5}}>{r.points} XP · {state.points>=r.points?t(lang,'active'):t(lang,'locked')}</Txt></GlassCard>)}</Screen>}
function Missions({state,goBack}){const lang=state.language;return <Screen><Header title={t(lang,'missions')} sub={`${state.completedMissions.length}/4`} goBack={goBack}/>{MISSIONS.map(m=><GlassCard key={m.id} style={{marginBottom:9,flexDirection:'row',alignItems:'center',gap:12}}><View style={[styles.missionIcon,state.completedMissions.includes(m.id)&&{backgroundColor:'#fff'}]}><Ionicons name={state.completedMissions.includes(m.id)?'checkmark':'flag-outline'} size={19} color={state.completedMissions.includes(m.id)?'#050506':'#fff'}/></View><View style={{flex:1}}><Txt style={{fontWeight:'900'}}>{lang==='cs'?m.titleCs:m.titleEn}</Txt><Txt muted style={{fontSize:9,marginTop:4}}>+{m.xp} XP</Txt></View></GlassCard>)}</Screen>}
function Crew({state,actions,goBack}){return <Screen><Header title="MY CREW" sub="MY XXL" goBack={goBack}/><GlassCard><View style={styles.profileRow}><View style={{flex:1}}><Txt style={{fontWeight:'900'}}>Share festival zone</Txt><Txt muted style={{fontSize:10,marginTop:4}}>Local prototype only.</Txt></View><Switch value={state.crewShare} onValueChange={actions.setCrewShare} trackColor={{false:'#292930',true:COLORS.green}} thumbColor="#fff"/></View></GlassCard></Screen>}
function LockedFeature({title,state,navigate,goBack}){const lang=state.language;if(state.session)return <Screen><Header title={title} sub="XXL CZECHIA 3.0" goBack={goBack}/><GlassCard style={styles.center}><Ionicons name="sparkles-outline" size={30} color="#fff"/><Txt style={{fontSize:21,fontWeight:'900',marginTop:16}}>{title}</Txt><Txt muted style={styles.centerCopy}>XXL CZECHIA 3.0 module · connected to your local account.</Txt></GlassCard></Screen>;return <Screen><Header title={title} sub={t(lang,'guest')} goBack={goBack}/><GlassCard style={styles.center}><Ionicons name="lock-closed-outline" size={30} color="#fff"/><Txt style={{fontSize:22,fontWeight:'900',marginTop:16}}>{t(lang,'accountRequired')}</Txt><Button green title={t(lang,'login')} onPress={()=>navigate('auth',{mode:'login'})} style={{marginTop:18,width:'100%'}}/></GlassCard></Screen>}
function Info({icon,t,last}){return <View style={[styles.info,!last&&styles.border]}><View style={styles.infoIcon}><Ionicons name={icon} size={19} color="#fff"/></View><Txt style={{flex:1,fontSize:11,fontWeight:'800'}}>{t}</Txt></View>}
function LangRow({title,active,onPress,last}){return <Pressable onPress={onPress} style={[styles.langRow,!last&&styles.border]}><Txt style={{flex:1,fontWeight:'900'}}>{title}</Txt>{active&&<Ionicons name="checkmark-circle" size={20} color={COLORS.green2}/>}</Pressable>}
function Stat({n,t}){return <GlassCard style={styles.stat}><Txt style={{fontSize:23,fontWeight:'900'}}>{n}</Txt><Txt faint style={{fontSize:7,fontWeight:'900',marginTop:4}}>{t}</Txt></GlassCard>}
const styles=StyleSheet.create({
 header:{height:82,flexDirection:'row',alignItems:'center',gap:12},back:{height:42,width:42,borderRadius:21,backgroundColor:COLORS.panel2,borderWidth:1,borderColor:COLORS.border,alignItems:'center',justifyContent:'center'},sub:{fontSize:8,fontWeight:'900',letterSpacing:1.4},title:{fontSize:25,fontWeight:'900',letterSpacing:-.8,marginTop:2},
 center:{alignItems:'center',paddingVertical:30},bigAvatar:{height:68,width:68,borderRadius:34,backgroundColor:'rgba(255,255,255,.07)',alignItems:'center',justifyContent:'center'},profileName:{fontSize:27,fontWeight:'900',marginTop:16},centerCopy:{fontSize:10,lineHeight:16,textAlign:'center',marginTop:7},
 profileRow:{flexDirection:'row',alignItems:'center',gap:12},userAvatar:{height:56,width:56,borderRadius:28,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},stats:{flexDirection:'row',flexWrap:'wrap',gap:9,justifyContent:'space-between'},stat:{width:'48.5%',alignItems:'center'},
 langRow:{minHeight:62,flexDirection:'row',alignItems:'center'},border:{borderBottomWidth:1,borderColor:COLORS.border},
 noteRow:{flexDirection:'row',alignItems:'flex-start',gap:11},noteIcon:{height:40,width:40,borderRadius:14,backgroundColor:'rgba(255,255,255,.07)',alignItems:'center',justifyContent:'center'},unread:{height:8,width:8,borderRadius:4,backgroundColor:COLORS.green},
 info:{minHeight:64,flexDirection:'row',alignItems:'center',gap:12},infoIcon:{height:39,width:39,borderRadius:14,backgroundColor:'rgba(255,255,255,.07)',alignItems:'center',justifyContent:'center'},emergency:{minHeight:255,justifyContent:'flex-end',backgroundColor:'#210A10'},
 missionIcon:{height:42,width:42,borderRadius:14,backgroundColor:'rgba(255,255,255,.07)',alignItems:'center',justifyContent:'center'},
});
