import React, {useMemo, useState} from 'react';
import { View, Pressable, StyleSheet } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { Screen, Txt, Pill, Button, SectionTitle, GlassCard } from '../components/UI';
import { COLORS, GRADIENTS } from '../theme';
import { EVENT } from '../data';

export default function PassScreen({ state, navigate }){
 const [showQr,setShowQr]=useState(false);
 return <Screen>
  <View style={styles.header}><View><Txt faint style={styles.eyebrow}>YOUR ACCESS</Txt><Txt style={styles.title}>XXL PASS</Txt></View><Pill active>ACTIVE</Pill></View>
  <LinearGradient colors={GRADIENTS.pass} style={styles.pass}>
    <View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><View><Txt style={styles.logo}>XXL</Txt><Txt faint style={styles.logoSub}>CZECHIA · PASS</Txt></View><Ionicons name="star" size={24} color="#fff"/></View>
    {!showQr?<>
      <View style={{marginTop:62}}><Txt faint style={styles.kicker}>{EVENT.name}</Txt><Txt style={styles.name}>ŠIMON SZÁBO</Txt><Txt muted style={styles.meta}>GENERAL ADMISSION · ZONE A</Txt></View>
      <View style={styles.details}><Detail label="EVENT" value="SEPT 2027"/><Detail label="VENUE" value="OSTRAVAR"/><Detail label="PASS" value="XXL-001"/></View>
      <Button title="SHOW ENTRY CODE" icon="qr-code-outline" onPress={()=>setShowQr(true)}/>
    </>:<>
      <View style={styles.qrWrap}><FakeQr seed="XXL-001-SIMON"/><Txt style={{color:'#050505',fontWeight:'1000',fontSize:15,marginTop:12}}>XXL-001-SIMON</Txt><Txt style={{color:'#777',fontWeight:'700',fontSize:10,marginTop:3}}>SCAN AT MAIN ENTRANCE</Txt></View>
      <Button title="HIDE ENTRY CODE" secondary onPress={()=>setShowQr(false)} style={{marginTop:18}}/>
    </>}
  </LinearGradient>
  <Txt faint style={{fontSize:10,lineHeight:16,textAlign:'center',paddingHorizontal:24,marginTop:12}}>Demo pass for the XXL PASS prototype. Final production QR must be generated by the ticketing backend.</Txt>
  <SectionTitle eyebrow="PASS TOOLS" title="Everything in one place"/>
  <GlassCard>
    <Tool icon="wallet-outline" title="Add to Apple Wallet" sub="Production integration ready for later."/>
    <Tool icon="person-outline" title="Pass holder" sub="Šimon Szábo · General Admission"/>
    <Tool icon="shield-checkmark-outline" title="Access status" sub="Active · ready for entry" last/>
  </GlassCard>
  <Button title="OPEN VENUE MAP" secondary icon="map-outline" onPress={()=>navigate('map')} style={{marginTop:12}}/>
 </Screen>
}
function Detail({label,value}){return <View style={{flex:1}}><Txt faint style={{fontSize:8,fontWeight:'900',letterSpacing:1.2}}>{label}</Txt><Txt style={{fontSize:12,fontWeight:'900',marginTop:5}}>{value}</Txt></View>}
function Tool({icon,title,sub,last}){return <View style={[styles.tool,!last&&styles.toolBorder]}><View style={styles.toolIcon}><Ionicons name={icon} size={19} color="#fff"/></View><View style={{flex:1}}><Txt style={{fontWeight:'900'}}>{title}</Txt><Txt muted style={{fontSize:11,marginTop:3}}>{sub}</Txt></View><Ionicons name="chevron-forward" size={17} color={COLORS.faint}/></View>}
function FakeQr({seed}){const cells=useMemo(()=>Array.from({length:121},(_,i)=>{let n=0;for(let c=0;c<seed.length;c++)n=(n+seed.charCodeAt(c)*(i+7)*(c+3))%97;return ((n+i*11)%5)<2;}),[seed]);return <View style={styles.qr}>{cells.map((on,i)=><View key={i} style={[styles.cell,{backgroundColor:on?'#050505':'#fff'}]}/>)}</View>}
const styles=StyleSheet.create({header:{height:100,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.6},title:{fontSize:38,fontWeight:'1000',letterSpacing:-2,marginTop:2},pass:{minHeight:520,borderRadius:34,borderWidth:1,borderColor:COLORS.borderStrong,padding:22,overflow:'hidden'},logo:{fontSize:30,fontWeight:'1000',letterSpacing:-1.8},logoSub:{fontSize:8,fontWeight:'900',letterSpacing:2},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.5},name:{fontSize:30,fontWeight:'1000',letterSpacing:-1,marginTop:8},meta:{fontSize:11,fontWeight:'800',marginTop:7},details:{flexDirection:'row',borderTopWidth:1,borderBottomWidth:1,borderColor:COLORS.border,marginVertical:28,paddingVertical:18},qrWrap:{backgroundColor:'#fff',padding:20,borderRadius:28,alignItems:'center',marginTop:36},qr:{width:220,height:220,flexDirection:'row',flexWrap:'wrap',backgroundColor:'#fff',padding:7},cell:{width:18,height:18},tool:{minHeight:66,flexDirection:'row',alignItems:'center',gap:12},toolBorder:{borderBottomWidth:1,borderColor:COLORS.border},toolIcon:{width:38,height:38,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,255,255,.07)'}});
