import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Animated,View,Pressable,StyleSheet} from 'react-native';
import {LinearGradient} from 'expo-linear-gradient';
import {Ionicons} from '@expo/vector-icons';
import {Screen,Txt,Pill,Button,SectionTitle,GlassCard,XXLMark} from '../components/UI';
import {COLORS,GRADIENTS} from '../theme';
import {EVENT} from '../data';

export default function PassScreen({navigate}){
 const [showQr,setShowQr]=useState(false);
 const shimmer=useRef(new Animated.Value(-1)).current;
 useEffect(()=>{
  const loop=Animated.loop(Animated.sequence([
   Animated.timing(shimmer,{toValue:1,duration:2200,useNativeDriver:true}),
   Animated.delay(800),
   Animated.timing(shimmer,{toValue:-1,duration:0,useNativeDriver:true}),
  ]));
  loop.start();
  return()=>loop.stop();
 },[shimmer]);
 const x=shimmer.interpolate({inputRange:[-1,1],outputRange:[-260,360]});

 return <Screen>
  <View style={styles.header}><View><Txt faint style={styles.eyebrow}>YOUR ACCESS</Txt><Txt style={styles.title}>XXL PASS</Txt></View><Pill active>ACTIVE</Pill></View>

  <LinearGradient colors={GRADIENTS.pass} style={styles.pass}>
   <View style={styles.chromeRingOne}/><View style={styles.chromeRingTwo}/>
   <Animated.View pointerEvents="none" style={[styles.shimmer,{transform:[{translateX:x},{rotate:'16deg'}]}]}><LinearGradient colors={['transparent','rgba(255,255,255,.16)','transparent']} style={{flex:1}}/></Animated.View>
   <View style={styles.passTop}><XXLMark small/><View style={styles.typeBadge}><Txt style={{fontSize:8,fontWeight:'900',color:'#050506',letterSpacing:1}}>GA</Txt></View></View>

   {!showQr?<>
    <View style={styles.identity}><Txt faint style={styles.kicker}>{EVENT.name}</Txt><Txt style={styles.name}>ŠIMON SZÁBO</Txt><Txt muted style={styles.meta}>GENERAL ADMISSION · ZONE A</Txt></View>
    <View style={styles.details}><Detail label="EVENT" value="SEP 2027"/><Detail label="VENUE" value="OSTRAVAR"/><Detail label="PASS" value="XXL-001"/></View>
    <View style={styles.accessRow}><View><Txt faint style={styles.accessLabel}>ENTRY STATUS</Txt><Txt style={styles.accessValue}>READY FOR ENTRY</Txt></View><Ionicons name="shield-checkmark" size={24} color="#fff"/></View>
    <Button title="REVEAL ENTRY CODE" icon="qr-code-outline" onPress={()=>setShowQr(true)} style={{marginTop:18}}/>
   </>:<>
    <View style={styles.qrWrap}><FakeQr seed="XXL-001-SIMON"/><Txt style={styles.qrCode}>XXL-001-SIMON</Txt><Txt style={styles.qrHint}>SCAN AT MAIN ENTRANCE</Txt></View>
    <Button title="HIDE ENTRY CODE" secondary onPress={()=>setShowQr(false)} style={{marginTop:18}}/>
   </>}
  </LinearGradient>

  <View style={styles.security}><Ionicons name="lock-closed-outline" size={14} color={COLORS.faint}/><Txt faint style={{fontSize:9,lineHeight:15,flex:1}}>Demo access credential. Production entry codes should rotate and be generated by the ticketing backend.</Txt></View>

  <SectionTitle eyebrow="PASS ACTIONS" title="Your access tools"/>
  <GlassCard style={{paddingVertical:4}}>
   <Tool icon="wallet-outline" title="Add to Apple Wallet" sub="Wallet pass integration placeholder"/>
   <Tool icon="map-outline" title="Find your entrance" sub="Zone A · Main Entrance" onPress={()=>navigate('map')}/>
   <Tool icon="shield-checkmark-outline" title="Access status" sub="Active · ready for event day" last/>
  </GlassCard>
 </Screen>
}

function Detail({label,value}){return <View style={{flex:1}}><Txt faint style={styles.detailLabel}>{label}</Txt><Txt style={styles.detailValue}>{value}</Txt></View>}
function Tool({icon,title,sub,last,onPress}){return <Pressable onPress={onPress} disabled={!onPress} style={[styles.tool,!last&&styles.toolBorder]}><View style={styles.toolIcon}><Ionicons name={icon} size={19} color="#fff"/></View><View style={{flex:1}}><Txt style={{fontWeight:'900'}}>{title}</Txt><Txt muted style={{fontSize:11,marginTop:3}}>{sub}</Txt></View><Ionicons name="chevron-forward" size={17} color={COLORS.faint}/></Pressable>}
function FakeQr({seed}){const cells=useMemo(()=>Array.from({length:144},(_,i)=>{let n=0;for(let c=0;c<seed.length;c++)n=(n+seed.charCodeAt(c)*(i+11)*(c+5))%131;return ((n+i*13)%7)<3;}),[seed]);return <View style={styles.qr}>{cells.map((on,i)=><View key={i} style={[styles.cell,{backgroundColor:on?'#050506':'#fff'}]}/>)}</View>}

const styles=StyleSheet.create({
 header:{height:96,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},
 eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.6},
 title:{fontSize:40,fontWeight:'900',letterSpacing:-2,marginTop:2},
 pass:{minHeight:560,borderRadius:36,borderWidth:1,borderColor:COLORS.borderStrong,padding:22,overflow:'hidden'},
 passTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},
 typeBadge:{height:42,width:42,borderRadius:21,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},
 chromeRingOne:{position:'absolute',height:220,width:220,borderRadius:120,borderWidth:1,borderColor:'rgba(255,255,255,.08)',right:-100,top:65},
 chromeRingTwo:{position:'absolute',height:120,width:120,borderRadius:70,borderWidth:18,borderColor:'rgba(255,255,255,.02)',left:-45,bottom:55},
 shimmer:{position:'absolute',top:-80,bottom:-80,width:92},
 identity:{marginTop:72},
 kicker:{fontSize:8,fontWeight:'900',letterSpacing:1.6},
 name:{fontSize:31,fontWeight:'900',letterSpacing:-1.2,marginTop:8},
 meta:{fontSize:10,fontWeight:'800',marginTop:6},
 details:{flexDirection:'row',borderTopWidth:1,borderBottomWidth:1,borderColor:COLORS.border,marginTop:28,paddingVertical:19},
 detailLabel:{fontSize:7,fontWeight:'900',letterSpacing:1.2},
 detailValue:{fontSize:12,fontWeight:'900',marginTop:5},
 accessRow:{marginTop:23,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},
 accessLabel:{fontSize:7,fontWeight:'900',letterSpacing:1.3},
 accessValue:{fontSize:13,fontWeight:'900',marginTop:5},
 qrWrap:{backgroundColor:'#fff',padding:19,borderRadius:29,alignItems:'center',marginTop:40},
 qr:{width:228,height:228,flexDirection:'row',flexWrap:'wrap',backgroundColor:'#fff',padding:6},
 cell:{width:18,height:18},
 qrCode:{color:'#050506',fontWeight:'900',fontSize:14,marginTop:12},
 qrHint:{color:'#777',fontWeight:'800',fontSize:9,marginTop:4,letterSpacing:.8},
 security:{flexDirection:'row',gap:8,alignItems:'flex-start',paddingHorizontal:16,marginTop:13},
 tool:{minHeight:68,flexDirection:'row',alignItems:'center',gap:12},
 toolBorder:{borderBottomWidth:1,borderColor:COLORS.border},
 toolIcon:{width:40,height:40,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,255,255,.07)'},
});
